site_name: MkDocs Flow Player Demo
docs_dir: docs
site_dir: site

plugins:
  - search
  - flow-player:
      validation: strict

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
